INSERT INTO 
    bonuses (name, percent, tier, condition, low_threshold, high_threshold, low_reward_points, high_reward_points, per_bird) 
VALUES
    ('Anatomist', 25, 'b', '{"type": "miscellaneous", "value": "anatomist"}', 2, 4, 3, 7, NULL),
    ('Backyard Birder', 43, 'd', '{"type": "miscellaneous", "value": "backyard_birder"}', 5, 6, 3, 6, NULL),
    ('Bird Counter', 15, 'a', '{"type": "miscellaneous", "value": "bird_counter"}', NULL, NULL, NULL, NULL, 2),
    ('Bird Feeder', 43, 'd', '{"type": "food_cost", "value": "seed"}', 5, 8, 3, 7, NULL),
    ('Breeding Manager', 28, 'c', '{"type": "miscellaneous", "value": "breeding_manager"}', NULL, NULL, NULL, NULL, 1),
    ('Cartographer', 21, 'b', '{"type": "miscellaneous", "value": "cartographer"}', 2, 4, 3, 7, NULL),
    ('Ecologist', 0, 'a', '{"type": "miscellaneous", "value": "ecologist"}', NULL, NULL, NULL, NULL, 2),
    ('Enclosure Builder', 33, 'b', '{"type": "nest_type_count", "value": "ground"}', 4, 6, 4, 7, NULL),
    ('Falconer', 13, 's', '{"type": "miscellaneous", "value": "falconer"}', NULL, NULL, NULL, NULL, 2),
    ('Fishery Manager', 17, 'b', '{"type": "food_cost", "value": "fish"}', 2, 4, 3, 8, NULL),
    ('Food Web Expert', 11, 'b', '{"type": "food_cost", "value": "invertebrate"}', NULL, NULL, NULL, NULL, 2),
    ('Forester', 24, 'c', '{"type": "habitat_count", "value": "forest"}', 3, 5, 4, 8, NULL),
    ('Historian', 11, 'b', '{"type": "miscellaneous", "value": "historian"}', NULL, NULL, NULL, NULL, 2),
    ('Large Bird Specialist', 34, 'a', '{"type": "wingspan_greater", "value": 65}', 4, 6, 3, 6, NULL),
    ('Nest Box Builder', 32, 'c', '{"type": "nest_type_count", "value": "cavity"}', 4, 6, 4, 7, NULL),
    ('Omnivore Specialist', 17, 's', '{"type": "food_cost", "value": "wild"}', NULL, NULL, NULL, NULL, 2),
    ('Oologist', 0, 's', '{"type": "miscellaneous", "value": "oologist"}', 7, 9, 3, 6, NULL),
    ('Passerine Specialist', 35, 'd', '{"type": "wingspan_less", "value": 30}', 4, 6, 3, 6, NULL),
    ('Photographer', 35, 'c', '{"type": "miscellaneous", "value": "photographer"}', 4, 6, 3, 7, NULL),
    ('Platform Builder', 31, 'a', '{"type": "nest_type_count", "value": "platform"}', 4, 6, 4, 7, NULL),
    ('Prairie Manager', 18, 'b', '{"type": "habitat_count", "value": "grassland"}', 2, 4, 3, 8, NULL),
    ('Rodentologist', 14, 's', '{"type": "food_cost", "value": "rodent"}', NULL, NULL, NULL, NULL, 2),
    ('Visionary Leader', 0, 'd', '{"type": "miscellaneous", "value": "visionary_leader"}', 5, 8, 4, 7, NULL),
    ('Viticulturalist', 21, 'b', '{"type": "food_cost", "value": "fruit"}', 2, 4, 3, 7, NULL),
    ('Wetland Scientist', 27, 'c', '{"type": "habitat_count", "value": "wetland"}', 3, 5, 3, 7, NULL),
    ('Wildlife Gardener', 32, 'c', '{"type": "nest_type_count", "value": "cup"}', 4, 6, 4, 7, NULL);