INSERT INTO 
    birds (name, tier, victory_points, nest_type, egg_limit, wingspan, power_trigger, power, total_food_cost, is_predator, is_flocking, has_bonus_card_power)
VALUES
    ('Acorn Woodpecker', 'u', 5, 'cavity', 4, 46, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('American Avocet', 'c', 6, 'ground', 2, 79, 'once_between_turns', '{"type": "lay_egg_on_player_action", "value": "ground"}', 3, 0, 0, 0),
    ('American Bittern', 'c', 7, 'platform', 2, 107, 'when_activated', '{"type": "draw_cards_if_fewest", "value": 1}', 3, 0, 0, 0),
    ('American Coot', 'c', 3, 'platform', 5, 61, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 2, 0, 1, 0),
    ('American Crow', 'b', 4, 'platform', 2, 99, 'when_activated', '{"type": "discard_to_gain", "value": "wild"}', 1, 0, 0, 0),
    ('American Goldfinch', 'u', 3, 'bowl', 3, 23, 'when_played', '{"type": "gain_resource", "value": "seed"}', 2, 0, 0, 0),
    ('American Kestrel', 'u', 5, 'cavity', 3, 56, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 2, 1, 0, 0),
    ('American Oystercatcher', 'u', 5, 'ground', 2, 81, 'when_played', '{"type": "draw_cards_sharing", "value": 1}', 2, 0, 0, 0),
    ('American Redstart', 'b', 4, 'bowl', 2, 20, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 2, 0, 0, 0),
    ('American Robin', 'b', 1, 'bowl', 4, 43, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 1, 0, 1, 0),
    ('American White Pelican', 'u', 5, 'ground', 1, 274, 'when_activated', '{"type": "discard_to_tuck", "value": 2}', 2, 0, 1, 0),
    ('American Woodcock', 'b', 9, 'ground', 2, 46, NULL, NULL, 3, 0, 0, 0),
    ('Anhinga', 'u', 6, 'platform', 2, 114, 'when_activated', '{"type": "cache_if_die_matches", "value": "fish"}', 2, 1, 0, 0),
    ('Anna''s Hummingbird', 'b', 4, 'bowl', 2, 13, 'when_activated', '{"type": "all_players_gain_resource_from_feeder", "value": 1}', 1, 0, 0, 0),
    ('Ash-Throated Flycatcher', 'u', 4, 'cavity', 4, 30, 'when_played', '{"type": "lay_eggs_on_nest_type", "value": "cavity"}', 3, 0, 0, 0),
    ('Atlantic Puffin', 'a', 8, 'star', 1, 53, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Baird''s Sparrow', 'b', 3, 'ground', 2, 23, 'when_activated', '{"type": "lay_eggs", "value": 1}', 2, 0, 0, 0),
    ('Bald Eagle', 'b', 9, 'platform', 1, 203, 'when_played', '{"type": "gain_all_resource_from_feeder", "value": "fish"}', 3, 0, 0, 0),
    ('Baltimore Oriole', 'b', 9, 'star', 2, 30, 'when_activated', '{"type": "all_players_gain_resource", "value": "fruit"}', 3, 0, 0, 0),
    ('Barn Owl', 'u', 5, 'cavity', 4, 107, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 2, 1, 0, 0),
    ('Barn Swallow', 'a', 1, 'star', 3, 38, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 1, 0, 1, 0),
    ('Barred Owl', 'u', 3, 'cavity', 2, 107, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 75}', 1, 1, 0, 0),
    ('Barrow''s Goldeneye', 'c', 5, 'cavity', 4, 71, 'once_between_turns', '{"type": "lay_egg_on_player_action", "value": "cavity"}', 3, 0, 0, 0),
    ('Bell''s Vireo', 'b', 4, 'star', 2, 18, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 2, 0, 0, 1),
    ('Belted Kingfisher', 'c', 4, 'star', 4, 53, 'once_between_turns', '{"type": "gain_on_player_action", "value": "wetland"}', 2, 0, 0, 0),
    ('Bewick''s Wren', 'u', 4, 'cavity', 3, 18, 'when_activated', '{"type": "move_bird", "value": "any"}', 3, 0, 0, 0),
    ('Black Skimmer', 'u', 6, 'ground', 2, 112, 'when_activated', '{"type": "cache_if_die_matches", "value": "fish"}', 2, 1, 0, 0),
    ('Black Tern', 'c', 4, 'star', 2, 61, 'when_activated', '{"type": "draw_and_discard", "value": 1}', 1, 0, 0, 0),
    ('Black Vulture', 'u', 2, 'cavity', 1, 150, 'once_between_turns', '{"type": "gain_resource_on_predator_success", "value": 1}', 0, 0, 0, 0),
    ('Black-Bellied Whistling-Duck', 'u', 2, 'cavity', 5, 76, 'when_activated', '{"type": "discard_to_tuck", "value": 2}', 2, 0, 1, 0),
    ('Black-Billed Magpie', 'u', 3, 'star', 3, 64, 'once_between_turns', '{"type": "gain_resource_on_predator_success", "value": 1}', 2, 0, 0, 0),
    ('Black-Chinned Hummingbird', 'u', 4, 'bowl', 2, 8, 'when_activated', '{"type": "all_players_gain_resource", "value": "fruit"}', 1, 0, 0, 0),
    ('Black-Crowned Night-Heron', 'u', 9, 'platform', 2, 112, 'when_activated', '{"type": "discard_to_gain", "value": "wild"}', 3, 0, 0, 0),
    ('Black-Necked Stilt', 'u', 4, 'ground', 2, 74, 'when_played', '{"type": "draw_cards", "value": 2}', 2, 0, 0, 0),
    ('Blue Grosbeak', 'u', 4, 'bowl', 3, 28, 'when_activated', '{"type": "move_bird", "value": "any"}', 3, 0, 0, 0),
    ('Blue Jay', 'u', 3, 'bowl', 2, 41, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 2, 0, 0, 0),
    ('Blue-Gray Gnatcatcher', 'u', 1, 'bowl', 3, 15, 'when_activated', '{"type": "gain_resource", "value": "invertebrate"}', 1, 0, 0, 0),
    ('Blue-Winged Warbler', 'u', 8, 'bowl', 2, 20, NULL, NULL, 2, 0, 0, 0),
    ('Bobolink', 'c', 4, 'ground', 3, 30, 'when_played', '{"type": "lay_eggs_on_nest_type", "value": "ground"}', 3, 0, 0, 0),
    ('Brant', 'u', 3, 'ground', 2, 114, 'when_played', '{"type": "draw_face_up_cards", "value": 3}', 2, 0, 0, 0),
    ('Brewer''s Blackbird', 'c', 3, 'bowl', 3, 41, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 2, 0, 1, 0),
    ('Broad-Winged Hawk', 'u', 4, 'platform', 2, 85, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 1, 1, 0, 0),
    ('Bronzed Cowbird', 'c', 5, NULL, 0, 36, 'once_between_turns', '{"type": "lay_egg_on_player_action", "value": "cup"}', 2, 0, 0, 0),
    ('Brown Pelican', 'u', 4, 'platform', 2, 201, 'when_played', '{"type": "gain_resource", "value": "fish"}', 2, 0, 0, 0),
    ('Brown-Headed Cowbird', 'u', 3, NULL, 0, 30, 'once_between_turns', '{"type": "lay_egg_on_player_action", "value": "cup"}', 1, 0, 0, 0),
    ('Burrowing Owl', 'u', 5, 'star', 4, 53, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 2, 1, 0, 0),
    ('Bushtit', 'b', 2, 'star', 5, 15, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 2, 0, 1, 0),
    ('California Condor', 'u', 1, 'ground', 1, 277, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 0, 0, 0, 1),
    ('California Quail', 'a', 3, 'ground', 6, 36, 'when_activated', '{"type": "lay_eggs", "value": 1}', 3, 0, 0, 0),
    ('Canada Goose', 'c', 3, 'ground', 3, 132, 'when_activated', '{"type": "discard_to_tuck", "value": 2}', 2, 0, 1, 0),
    ('Canvasback', 'u', 4, 'star', 4, 82, 'when_activated', '{"type": "all_players_draw_cards", "value": 1}', 2, 0, 0, 0),
    ('Carolina Chickadee', 'b', 2, 'cavity', 3, 20, 'when_activated', '{"type": "cache_resource", "value": "seed"}', 1, 0, 0, 0),
    ('Carolina Wren', 'c', 1, 'cavity', 5, 20, 'when_played', '{"type": "draw_cards", "value": 2}', 1, 0, 0, 0),
    ('Cassin''s Finch', 'b', 4, 'bowl', 3, 30, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 2, 0, 0, 1),
    ('Cassin''s Sparrow', 'b', 3, 'ground', 2, 20, 'when_activated', '{"type": "lay_eggs", "value": 1}', 2, 0, 0, 0),
    ('Cedar Waxwing', 'c', 3, 'bowl', 3, 25, 'when_activated', '{"type": "tuck_and_gain", "value": "fruit"}', 2, 0, 1, 0),
    ('Cerulean Warbler', 'b', 4, 'bowl', 2, 20, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 2, 0, 0, 1),
    ('Chestnut-Collared Longspur', 'u', 5, 'ground', 4, 25, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Chihuahuan Raven', 's', 4, 'platform', 3, 112, 'when_activated', '{"type": "discard_to_gain", "value": "wild"}', 3, 0, 0, 0),
    ('Chimney Swift', 'u', 3, 'star', 2, 36, 'when_activated', '{"type": "move_bird", "value": "any"}', 2, 0, 0, 0),
    ('Chipping Sparrow', 'a', 1, 'bowl', 3, 23, 'when_activated', '{"type": "lay_eggs", "value": 1}', 1, 0, 0, 0),
    ('Clark''s Grebe', 'c', 5, 'star', 2, 61, 'when_activated', '{"type": "draw_and_discard", "value": 1}', 1, 0, 0, 0),
    ('Clark''s Nutcracker', 'u', 5, 'platform', 2, 61, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('Common Grackle', 'b', 3, 'bowl', 3, 43, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 2, 0, 1, 0),
    ('Common Loon', 'u', 6, 'ground', 1, 117, 'when_activated', '{"type": "draw_cards_if_fewest", "value": 1}', 2, 0, 0, 0),
    ('Common Merganser', 'u', 5, 'cavity', 4, 86, 'when_activated', '{"type": "cache_if_die_matches", "value": "fish"}', 2, 1, 0, 0),
    ('Common Nighthawk', 'u', 3, 'ground', 2, 56, 'when_activated', '{"type": "move_bird", "value": "any"}', 2, 0, 0, 0),
    ('Common Raven', 's', 5, 'platform', 2, 135, 'when_activated', '{"type": "discard_to_gain", "value": "wild"}', 3, 0, 0, 0),
    ('Common Yellowthroat', 'a', 1, 'bowl', 4, 18, 'when_activated', '{"type": "draw_and_discard", "value": 2}', 1, 0, 0, 0),
    ('Cooper''s Hawk', 'u', 3, 'platform', 2, 79, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 75}', 1, 1, 0, 0),
    ('Dark-Eyed Junco', 'u', 3, 'ground', 3, 23, 'when_activated', '{"type": "tuck_and_gain", "value": "seed"}', 2, 0, 1, 0),
    ('Dickcissel', 'u', 4, 'ground', 3, 25, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 3, 0, 1, 0),
    ('Double-Crested Cormorant', 'u', 3, 'platform', 3, 132, 'when_activated', '{"type": "discard_to_tuck", "value": 2}', 2, 0, 1, 0),
    ('Downy Woodpecker', 'c', 3, 'cavity', 2, 30, 'when_played', '{"type": "play_additional_bird", "value": "forest"}', 1, 0, 0, 0),
    ('Eastern Bluebird', 'c', 4, 'cavity', 5, 33, 'when_played', '{"type": "play_additional_bird", "value": "grassland"}', 2, 0, 0, 0),
    ('Eastern Kingbird', 'u', 2, 'bowl', 2, 38, 'once_between_turns', '{"type": "gain_on_player_action", "value": "forest"}', 1, 0, 0, 0),
    ('Eastern Phoebe', 'b', 3, 'star', 4, 28, 'when_activated', '{"type": "all_players_gain_resource", "value": "invertebrate"}', 1, 0, 0, 0),
    ('Eastern Screech-Owl', 'u', 4, 'cavity', 2, 51, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 1, 1, 0, 0),
    ('Ferruginous Hawk', 'u', 6, 'platform', 2, 142, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 2, 1, 0, 0),
    ('Fish Crow', 'b', 6, 'platform', 2, 91, 'when_activated', '{"type": "discard_to_gain", "value": "wild"}', 2, 0, 0, 0),
    ('Forster''s Tern', 'c', 4, 'star', 2, 79, 'when_activated', '{"type": "draw_and_discard", "value": 1}', 1, 0, 0, 0),
    ('Franklin''s Gull', 's', 3, 'star', 2, 91, 'when_activated', '{"type": "discard_to_draw", "value": 2}', 2, 0, 0, 0),
    ('Golden Eagle', 'b', 8, 'platform', 1, 201, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 100}', 3, 1, 0, 0),
    ('Grasshopper Sparrow', 'b', 2, 'ground', 2, 20, 'when_activated', '{"type": "lay_eggs", "value": 1}', 1, 0, 0, 0),
    ('Gray Catbird', 'b', 5, 'bowl', 3, 28, 'when_activated', '{"type": "repeat_habitat_power", "value": "any"}', 3, 0, 0, 0),
    ('Great Blue Heron', 'b', 5, 'platform', 2, 183, 'when_played', '{"type": "play_additional_bird", "value": "wetland"}', 2, 0, 0, 0),
    ('Great Crested Flycatcher', 'u', 5, 'cavity', 3, 33, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 2, 0, 0, 0),
    ('Great Egret', 'b', 7, 'platform', 3, 130, 'when_played', '{"type": "play_additional_bird", "value": "wetland"}', 3, 0, 0, 0),
    ('Great Horned Owl', 'b', 8, 'platform', 2, 112, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 100}', 3, 1, 0, 0),
    ('Greater Prairie-Chicken', 'u', 5, 'ground', 4, 71, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Greater Roadrunner', 'b', 7, 'platform', 2, 56, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 50}', 3, 1, 0, 0),
    ('Green Heron', 'c', 4, 'platform', 3, 66, 'when_activated', '{"type": "trade_resource", "value": "wild"}', 1, 0, 0, 0),
    ('Hermit Thrush', 'c', 7, 'star', 2, 30, 'when_activated', '{"type": "gain_resource_if_fewest", "value": 1}', 3, 0, 0, 0),
    ('Hooded Merganser', 'c', 5, 'cavity', 4, 61, 'when_activated', '{"type": "repeat_predator_power", "value": "habitat"}', 2, 0, 0, 0),
    ('Hooded Warbler', 'b', 7, 'bowl', 3, 18, NULL, NULL, 2, 0, 0, 0),
    ('Horned Lark', 'u', 5, 'ground', 4, 30, 'once_between_turns', '{"type": "gain_on_player_action", "value": "grassland"}', 2, 0, 1, 0),
    ('House Finch', 'b', 3, 'bowl', 6, 25, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 2, 0, 1, 0),
    ('House Wren', 'c', 1, 'cavity', 5, 15, 'when_played', '{"type": "play_additional_bird", "value": "any"}', 1, 0, 0, 0),
    ('Inca Dove', 'c', 2, 'platform', 4, 28, 'when_played', '{"type": "lay_eggs_on_nest_type", "value": "platform"}', 2, 0, 0, 0),
    ('Indigo Bunting', 'b', 5, 'bowl', 3, 20, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('Juniper Titmouse', 'c', 4, 'cavity', 3, 23, 'when_activated', '{"type": "cache_resource", "value": "seed"}', 2, 0, 0, 0),
    ('Killdeer', 's', 1, 'ground', 3, 46, 'when_activated', '{"type": "discard_to_draw", "value": 2}', 1, 0, 0, 0),
    ('King Rail', 'c', 4, 'platform', 6, 51, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Lazuli Bunting', 'c', 4, 'bowl', 4, 23, 'when_activated', '{"type": "all_players_lay_eggs_on_nest", "value": "cup"}', 3, 0, 0, 0),
    ('Lincoln''s Sparrow', 'u', 3, 'ground', 2, 20, 'when_activated', '{"type": "move_bird", "value": "any"}', 2, 0, 0, 0),
    ('Loggerhead Shrike', 'u', 3, 'bowl', 4, 30, 'once_between_turns', '{"type": "cache_on_player_action", "value": "rodent"}', 2, 0, 0, 0),
    ('Mallard', 'b', 0, 'ground', 4, 89, 'when_activated', '{"type": "draw_cards", "value": 1}', 1, 0, 0, 0),
    ('Mississippi Kite', 'c', 4, 'platform', 1, 79, 'when_activated', '{"type": "cache_if_die_matches", "value": "rodent"}', 1, 1, 0, 0),
    ('Mountain Bluebird', 'c', 4, 'cavity', 5, 36, 'when_played', '{"type": "play_additional_bird", "value": "grassland"}', 2, 0, 0, 0),
    ('Mountain Chickadee', 'b', 2, 'cavity', 3, 23, 'when_activated', '{"type": "cache_resource", "value": "seed"}', 1, 0, 0, 0),
    ('Mourning Dove', 'a', 0, 'platform', 5, 46, 'when_activated', '{"type": "lay_eggs", "value": 1}', 1, 0, 0, 0),
    ('Northern Bobwhite', 'c', 5, 'ground', 6, 33, 'when_activated', '{"type": "lay_eggs", "value": 1}', 3, 0, 0, 0),
    ('Northern Cardinal', 'c', 3, 'bowl', 5, 30, 'when_activated', '{"type": "gain_resource", "value": "fruit"}', 2, 0, 0, 0),
    ('Northern Flicker', 'u', 2, 'cavity', 4, 51, 'when_played', '{"type": "gain_all_resource_from_feeder", "value": "invertebrate"}', 1, 0, 0, 0),
    ('Northern Harrier', 'u', 3, 'platform', 2, 109, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 75}', 1, 1, 0, 0),
    ('Northern Mockingbird', 'b', 2, 'bowl', 4, 36, 'when_activated', '{"type": "repeat_habitat_power", "value": "any"}', 2, 0, 0, 0),
    ('Northern Shoveler', 'c', 7, 'ground', 4, 76, 'when_activated', '{"type": "all_players_draw_cards", "value": 1}', 3, 0, 0, 0),
    ('Osprey', 'c', 5, 'platform', 2, 160, 'when_activated', '{"type": "all_players_gain_resource", "value": "fish"}', 1, 0, 0, 0),
    ('Painted Bunting', 'c', 5, 'bowl', 4, 23, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Painted Whitestart', 'b', 1, 'ground', 3, 22, 'when_activated', '{"type": "gain_resource", "value": "invertebrate"}', 1, 0, 0, 0),
    ('Peregrine Falcon', 'u', 5, 'platform', 2, 104, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 100}', 2, 1, 0, 0),
    ('Pied-Billed Grebe', 'u', 0, 'platform', 4, 41, 'when_activated', '{"type": "draw_and_discard", "value": 2}', 1, 0, 0, 0),
    ('Pileated Woodpecker', 'b', 4, 'cavity', 2, 74, 'when_activated', '{"type": "all_players_lay_eggs_on_nest", "value": "cavity"}', 2, 0, 0, 0),
    ('Pine Siskin', 'u', 3, 'bowl', 2, 23, 'when_activated', '{"type": "tuck_and_gain", "value": "seed"}', 2, 0, 1, 0),
    ('Prothonotary Warbler', 'b', 8, 'cavity', 4, 23, NULL, NULL, 3, 0, 0, 0),
    ('Purple Gallinule', 'c', 7, 'platform', 4, 56, 'when_activated', '{"type": "all_players_draw_cards", "value": 1}', 3, 0, 0, 0),
    ('Purple Martin', 'a', 2, 'cavity', 3, 46, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 1, 0, 1, 0),
    ('Pygmy Nuthatch', 'u', 2, 'cavity', 4, 20, 'when_activated', '{"type": "tuck_and_gain", "value": "invertebrate"}', 2, 0, 1, 0),
    ('Red Crossbill', 'u', 6, 'bowl', 2, 28, 'when_activated', '{"type": "all_players_gain_resource", "value": "seed"}', 2, 0, 0, 0),
    ('Red-Bellied Woodpecker', 'u', 1, 'cavity', 3, 41, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 1, 0, 0, 0),
    ('Red-Breasted Merganser', 'u', 3, 'ground', 4, 78, 'when_activated', '{"type": "draw_and_discard", "value": 2}', 2, 0, 0, 0),
    ('Red-Breasted Nuthatch', 'u', 2, 'cavity', 3, 23, 'when_activated', '{"type": "cache_resource", "value": "seed"}', 1, 0, 0, 0),
    ('Red-Cockaded Woodpecker', 'u', 4, 'cavity', 2, 36, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 2, 0, 0, 1),
    ('Red-Eyed Vireo', 'u', 3, 'star', 2, 25, 'when_played', '{"type": "play_additional_bird", "value": "forest"}', 1, 0, 0, 0),
    ('Red-Headed Woodpecker', 'u', 4, 'cavity', 3, 43, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('Red-Shouldered Hawk', 'u', 3, 'platform', 2, 102, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 75}', 1, 1, 0, 0),
    ('Red-Tailed Hawk', 'u', 5, 'platform', 2, 124, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 75}', 2, 1, 0, 0),
    ('Red-Winged Blackbird', 'u', 2, 'bowl', 3, 33, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 1, 0, 1, 0),
    ('Ring-Billed Gull', 'u', 4, 'ground', 2, 122, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 2, 0, 1, 0),
    ('Rose-Breasted Grosbeak', 'u', 6, 'bowl', 3, 33, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('Roseate Spoonbill', 'b', 6, 'platform', 2, 127, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Ruby-Crowned Kinglet', 'u', 2, 'bowl', 3, 20, 'when_played', '{"type": "play_additional_bird", "value": "forest"}', 1, 0, 0, 0),
    ('Ruby-Throated Hummingbird', 'u', 4, 'bowl', 2, 10, 'when_activated', '{"type": "all_players_gain_resource_from_feeder", "value": 1}', 1, 0, 0, 0),
    ('Ruddy Duck', 'a', 0, 'platform', 5, 48, 'when_activated', '{"type": "draw_and_discard", "value": 2}', 1, 0, 0, 0),
    ('Sandhill Crane', 'c', 5, 'ground', 1, 196, 'when_activated', '{"type": "discard_to_tuck", "value": 2}', 3, 0, 1, 0),
    ('Savannah Sparrow', 'c', 2, 'ground', 3, 18, 'when_played', '{"type": "play_additional_bird", "value": "grassland"}', 1, 0, 0, 0),
    ('Say''s Phoebe', 'c', 5, 'bowl', 3, 33, 'when_played', '{"type": "lay_eggs_on_nest_type", "value": "cup"}', 3, 0, 0, 0),
    ('Scaled Quail', 'b', 0, 'ground', 6, 36, 'when_activated', '{"type": "lay_eggs", "value": 1}', 1, 0, 0, 0),
    ('Scissor-Tailed Flycatcher', 'b', 8, 'bowl', 2, 38, 'when_activated', '{"type": "all_players_gain_resource", "value": "invertebrate"}', 3, 0, 0, 0),
    ('Snowy Egret', 'c', 4, 'platform', 2, 104, 'when_activated', '{"type": "cache_if_die_matches", "value": "fish"}', 1, 1, 0, 0),
    ('Song Sparrow', 'u', 0, 'bowl', 5, 20, 'when_activated', '{"type": "move_bird", "value": "any"}', 1, 0, 0, 0),
    ('Spotted Owl', 'b', 5, 'cavity', 1, 102, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 2, 0, 0, 1),
    ('Spotted Sandpiper', 'c', 5, 'ground', 2, 38, 'when_activated', '{"type": "all_players_draw_cards", "value": 1}', 1, 0, 0, 0),
    ('Spotted Towhee', 'c', 0, 'ground', 4, 28, 'when_activated', '{"type": "gain_resource", "value": "seed"}', 1, 0, 0, 0),
    ('Sprague''s Pipit', 'c', 3, 'ground', 3, 25, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 2, 0, 0, 1),
    ('Steller''s Jay', 'u', 5, 'bowl', 2, 48, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('Swainson''s Hawk', 'u', 5, 'platform', 2, 130, 'when_activated', '{"type": "tuck_if_wingspan_less", "value": 75}', 2, 1, 0, 0),
    ('Tree Swallow', 'c', 3, 'cavity', 4, 38, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 2, 0, 1, 0),
    ('Trumpeter Swan', 'b', 9, 'ground', 2, 203, NULL, NULL, 3, 0, 0, 0),
    ('Tufted Titmouse', 'c', 2, 'cavity', 3, 25, 'when_played', '{"type": "play_additional_bird", "value": "forest"}', 1, 0, 0, 0),
    ('Turkey Vulture', 'u', 1, 'cavity', 1, 170, 'once_between_turns', '{"type": "gain_resource_on_predator_success", "value": 1}', 0, 0, 0, 0),
    ('Vaux''s Swift', 'u', 2, 'cavity', 3, 31, 'when_activated', '{"type": "tuck_and_gain", "value": "invertebrate"}', 1, 0, 1, 0),
    ('Violet-Green Swallow', 'u', 3, 'cavity', 3, 36, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 2, 0, 1, 0),
    ('Western Meadowlark', 'c', 2, 'ground', 4, 38, 'when_activated', '{"type": "all_players_lay_eggs_on_nest", "value": "ground"}', 2, 0, 0, 0),
    ('Western Tanager', 'c', 6, 'bowl', 2, 30, 'when_activated', '{"type": "gain_resource_from_feeder", "value": 1}', 3, 0, 0, 0),
    ('White-Breasted Nuthatch', 'u', 2, 'cavity', 3, 28, 'when_activated', '{"type": "cache_resource", "value": "seed"}', 1, 0, 0, 0),
    ('White-Crowned Sparrow', 'u', 2, 'ground', 5, 25, 'when_activated', '{"type": "move_bird", "value": "any"}', 2, 0, 0, 0),
    ('White-Faced Ibis', 'u', 8, 'platform', 2, 91, 'when_activated', '{"type": "cache_if_die_matches", "value": "fish"}', 3, 1, 0, 0),
    ('White-Throated Swift', 'u', 2, 'cavity', 2, 38, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 1, 0, 1, 0),
    ('Whooping Crane', 'b', 6, 'ground', 1, 221, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Wild Turkey', 'b', 8, 'ground', 5, 135, NULL, NULL, 3, 0, 0, 0),
    ('Willet', 'c', 4, 'ground', 2, 66, 'when_activated', '{"type": "cache_if_die_matches", "value": "fish"}', 1, 1, 0, 0),
    ('Wilson''s Snipe', 'c', 5, 'ground', 2, 41, 'when_activated', '{"type": "all_players_draw_cards", "value": 1}', 1, 0, 0, 0),
    ('Wood Duck', 'a', 4, 'cavity', 4, 76, 'when_activated', '{"type": "draw_and_discard", "value": 2}', 3, 0, 0, 0),
    ('Wood Stork', 'u', 6, 'platform', 2, 155, 'when_played', '{"type": "draw_bonus_card", "value": 1}', 3, 0, 0, 1),
    ('Yellow-Bellied Sapsucker', 'u', 3, 'cavity', 3, 41, 'when_activated', '{"type": "gain_resource", "value": "invertebrate"}', 2, 0, 0, 0),
    ('Yellow-Billed Cuckoo', 'u', 5, 'platform', 2, 46, 'once_between_turns', '{"type": "lay_egg_on_player_action", "value": "cup"}', 3, 0, 0, 0),
    ('Yellow-Breasted Chat', 'u', 5, 'bowl', 3, 25, 'when_activated', '{"type": "move_bird", "value": "any"}', 3, 0, 0, 0),
    ('Yellow-Headed Blackbird', 'u', 4, 'bowl', 3, 38, 'when_activated', '{"type": "tuck_and_lay_egg", "value": 1}', 2, 0, 1, 0),
    ('Yellow-Rumped Warbler', 'u', 1, 'bowl', 4, 23, 'when_activated', '{"type": "tuck_and_draw", "value": 1}', 1, 0, 1, 0);
